apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "insurance-ai-agents.fullname" . }}
  annotations:
    {{- if .Values.identity.awsRoleArn }}
    eks.amazonaws.com/role-arn: {{ .Values.identity.awsRoleArn | quote }}
    {{- end }}
    azure.workload.identity/client-id: {{ .Values.identity.azureClientId | quote }}
